[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[[plugins]]
  package = "netlify-plugin-prerender"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "netlify/functions"

  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
